
// -*- C++ -*-
// $Id: Version.h 88789 2010-01-31 07:05:17Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.

#define ACE_MAJOR_VERSION 5
#define ACE_MINOR_VERSION 7
#define ACE_BETA_VERSION 6
#define ACE_VERSION "5.7.6"
